logging:
  level:
    org:
      hibernate:
        SQL: debug
        type:
          descriptor: trace
spring:
  #  main:
  #    allow-circular-references: true
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/quizgame?createDatabaseIfNotExist=true
    username: root
    password: root

  jpa:
    #        The DB will be instasiate first before inserst
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create-drop
  sql:
    init:
      mode: always
  # For uploading files to our server
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  mvc:
    # For PUT, PATCH and DELTE on forms
    hiddenmethod:
      filter:
        enabled: true