insert into categories(id,name)
value (1,'Java'),
    (2,'Python'),
    (3,'PHP'),
    (4,'JavaScript');

insert into questions(id, question, option1, option2, option3, option4, answer, category_id)
    value (1,'What is a correct syntax to output Hello World in Java?','System.out.println(\"Hello World\");','print (\'Hello World\');','Console.WriteLine(\'Hello World\');','echo(\'Hello World\');','System.out.println(\"Hello World\");',1),
    (2,'Java is short for JavaScript?','False','True','Maybe','50/50','False',1),
    (3,'How do you insert COMMENTS in Java code? ','/*This is a comment','#This is a comment','//This is a comment','<!--This is a comment-->','//This is a comment',1),
    (4,'Which data type is used to create a variable that should store text?','string','String','myString','Txt','String',1),
    (5,'How do you create a variable with the numeric value 5?','x = 5;','float x = 5;','num x = 5;','int x = 5;','int x = 5;',1),
    (6,'How do you create a variable with the floating number 2.8?','x = 2.8f;','float x = 2.8f;','byte x = 2.8f;','int x = 2.8f;','float x = 2.8f;',1),
    (7,'Which method can be used to find the length of a string?','getLength()','getSize()','length()','len()','length()',1),
    (8,'Which operator is used to add together two values?','The + sign','The * sign','The ^ sign','The & sign','The + sign',1),
    (9,'Which method can be used to return a string in upper case letters?','tuc()','upperCase()','touppercase()','toUpperCase()','toUpperCase()',1),
    (10,'Which operator can be used to compare two values?','=','==','><','<>','==',1),
    (11,'To declare an array in Java, define the variable type with:','{}','()','[]','~~','[]',1),
    (12,'How do you create a method in Java?','methodName.','methodName[]','(methodName)','methodName()','methodName()',1),
    (13,'How do you call a method in Java?','methodName[];','(methodName);','methodName;','methodName();','methodName();',1),
    (14,'Which keyword is used to create a class in Java?','MyClass','class','className','class()','class',1),
    (15,'Which method can be used to find the highest value of x and y?','Math.Largest(x,y)','Math.maximum(x,y)','Math.max(x,y)','Math.maxNum(x,y)','Math.max(x,y)',1),
    (16,'Which operator is used to multiply numbers?','*','x','%','#','*',1),
    (17,'Which keyword is used to import a package from the Java API library?','import','package','lib','getlib','import',1),
    (18,'How do you start writing an if statement in Java?','if x > y:','if (x > y)','if x > y then:','if { x > y }','if (x > y)',1),
    (19,'How do you start writing a while loop in Java?','x > y while{','while x > y{','while x > y:','while (x > y){','while (x > y){',1),
    (20,'Which keyword is used to return a value inside a method?','void','break','get','return','return',1),

    (21,'What does PHP stand for?','PHP: Hypertext Preprocessor','Private Home Page','Personal Hypertext Processor','Programming Helps People','Personal Hypertext Processor',2),
    (22,'PHP server scripts are surrounded by delimiters, which?','<?php...?>','<&>...</&>','<?php>...</?>','<script>...</script>','<?php...?>',2),
    (23,'How do you write \'Hello World\' in PHP','\'Hello World\';','echo \'Hello World\';','Document.Write(\'Hello World\');','console.log(\'Hello World\')','echo \'Hello World\';',2),
    (24,'All variables in PHP start with which symbol?','$','%','&','!','$',2),
    (25,'What is the correct way to end a PHP statement?','.',';','New line','</php>',';',2),
    (26,'The PHP syntax is most similar to:','Perl and C','VBScript','JavaScript','Assembler','Perl and C',2),
    (27,'How do you get information from a form that is submitted using the \'get\' method?','$_GET[];','Request.Form','Request.QueryString','HTTPGET','$_GET[];',2),
    (28,'What is the correct way to include the file \'time.inc\' ?','<?php include file=\'time.inc\'; ?>','<?php include:\'time.inc\'; ?>','<!-- include file=\'time.inc\' -->',' <?php include \'time.inc\'; ?>','<?php include \'time.inc\'; ?>',2),
    (29,'What is the correct way to create a function in PHP?','new_function myFunction()','create myFunction()','function myFunction()','func myFunction()','function myFunction()',2),
    (30,'What is the correct way to open the file \'time.txt\' as readable?','open(\'time.txt\');','open(\'time.txt\',\'read\');','fopen(\'time.txt\',\'r+\');','fopen(\'time.txt\',\'r\');','fopen(\'time.txt\',\'r\');',2),
    (31,'Which superglobal variable holds information about headers, paths, and script locations?','$_SESSION','$_GET','$GLOBALS','$_SERVER','$_SERVER',2),
    (32,'What is the correct way to add 1 to the $count variable?','++count','$count=+1','count++;','$count++;','$count++;',2),
    (33,'What is a correct way to add a comment in PHP?','/*...*/','<!--...-->','*/.../*','<comment>...</comment>','/*...*/',2),
    (34,'Which one of these variables has an illegal name?','$my_Var','$my-Var','$myVar','#myVar','$my-Var',2),
    (35,'How do you create a cookie in PHP?','setcookie()','makecookie()','createcookie','selectcookie()','setcookie()',2),
    (36,'How do you create an array in PHP?','$cars = array(\'Volvo\', \'BMW\', \'Toyota\');','$cars = \'Volvo\', \'BMW\', \'Toyota\';','$cars = array[\'Volvo\', \'BMW\', \'Toyota\'];','$cars = array{\'Volvo\', \'BMW\', \'Toyota\'};','$cars = array(\'Volvo\', \'BMW\', \'Toyota\');',2),
    (37,'Which operator is used to check if two values are equal and of same data type?','!=','===','=','==','===',2),
    (38,'Which of the following type of variables are sequences of characters, like \'PHP supports string operations.\'?','Strings','Arrays','Objects','Resources','Strings',2),
    (39,'Which of the following magic constant of PHP returns function name?','_LINE_','_FILE_','_FUNCTION_','_CLASS_','_FUNCTION_',2),
    (40,'Which of the following array represents an array with a numeric index? ','Numeric Array','Associative Array','Multidimentional Array','None of the above','Numeric Array',2),

   (41, 'What is a correct syntax to output \'Hello World\' in Python?','print(\'Hello World\')','echo \'Hello World\'','echo(\'Hello World\');','p(\'Hello World\')','print(\'Hello World\')',3),
(42,'How do you insert COMMENTS in Python code?','#Comment','//Comment','/*Comment*/','%Comment%','#Comment',3),
(43,'Which one is NOT a legal variable name?','Myvar','my-var','_myvar','my_var','my-var',3),
(44,'How do you start writing a while loop in Python?','while (x > y)','x > y while {','while x > y {','while x > y:','while x > y:',3),
(45,'What is the correct file extension for Python files?','.pt','.pyt','.pyth','.py','.py',3),
(46,'How do you start writing a for loop in Python?','for x > y:','for each x in y:','foreach(x in y)','for x in y:','for x in y:',3),
(47,'What is the correct syntax to output the type of a variable or object in Python?','print(typeOf(x))','print(type(x))','print(typeof(x))','print(typeof x)','print(type(x))',3),
(48,'What is the correct way to create a function in Python?','function myfunction():','def myFunction():','create myFunction():','func myFunction():','def myFunction():',3),
(49,'What is a correct syntax to return the first character in a string?','x = sub(\'Hello\', 0, 1)','x = \'Hello\'.sub(0, 1)','x = \'Hello\'[0]','x = \'Hello\'.charAt(0)','x = \'Hello\'[0]',3),
(50,'Which method can be used to remove any whitespace from both the beginning and the end of a string?','trim()','strip()','len()','ptrim()','strip()',3),
(51,'Which method can be used to return a string in upper case letters?','upper()','toUpperCase()','upperCase()','uppercase()','upper()',3),
(52,'Which method can be used to replace parts of a string?','replaceString()','replace()','switch()','repl()','replace()',3),
(53,'Which operator is used to multiply numbers?','#','x','%','*','*',3),
(54,'Which operator can be used to compare two values?','><','==','=','<>','==',3),
(55,'Which of these collections defines a LIST?','{\'name\': \'apple\', \'color\': \'green\'}','[\'apple\', \'banana\', \'cherry\']','[\'apple\', \'banana\', \'cherry\']','{\'apple\', \'banana\', \'cherry\'}','[\'apple\', \'banana\', \'cherry\']',3),
(56,'Which of these collections defines a TUPLE?','[\'apple\', \'banana\', \'cherry\']','{\'apple\', \'banana\', \'cherry\'}','(\'apple\', \'banana\', \'cherry\')','{\'name\': \'apple\', \'color\': \'green\'}','(\'apple\', \'banana\', \'cherry\')',3),
(57,'Which of these collections defines a SET?','{\'apple\', \'banana\', \'cherry\'}','(\'apple\', \'banana\', \'cherry\')','[\'apple\', \'banana\', \'cherry\']','{\'name\': \'apple\', \'color\': \'green\'}','{\'apple\', \'banana\', \'cherry\'}',3),
(58,'Which of these collections defines a DICTIONARY?','(\'apple\', \'banana\', \'cherry\')','[\'apple\', \'banana\', \'cherry\']','{\'name\': \'apple\', \'color\': \'green\'}','{\'apple\', \'banana\', \'cherry\'}','{\'name\': \'apple\', \'color\': \'green\'}',3),
(59,'Which collection is ordered, changeable, and allows duplicate members?','DICTIONARY','LIST','SET','TUPLE','LIST',3),
(60,'Which collection does not allow duplicate members?','TUPLE','SET','LIST','ARRAY','SET',3),

    (61,'Inside which HTML element do we put the JavaScript?','<scripting>','<js>','<script>','<javascript>','<script>',4),
(62,'Where is the correct place to insert a JavaScript?','Both the <head> section and the <body> section are correct','The <body> section','The <head> section','Wherever I want','Both the <head> section and the <body> section are correct',4),
(63,'What is the correct syntax for referring to an external script called \'xxx.js\'?','<script href=\'xxx.js\'>','<script src=\'xxx.js\'>','<script name=\'xxx.js\'>','<script source=\'xxx.js\'>','<script src=\'xxx.js\'>',4),
(64,'How do you write \'Hello World\' in an alert box?','msgBox(\'Hello World\');','msg(\'Hello World\');','alertBox(\'Hello World\');','alert(\'Hello World\');','alert(\'Hello World\');',4),
(65,'How do you create a function in JavaScript?','function = myFunction()','function myFunction()','function:myFunction()','function<>myFunction()','function myFunction()',4),
(66,'How do you call a function named \'myFunction\'?','call function myFunction()','call myFunction()','myFunction()','func myFunction()','myFunction()',4),
(67,'How to write an IF statement in JavaScript?','if (i == 5)','if i = 5 then','if i == 5 then','if i = 5','if (i == 5)',4),
(68,'How to write an IF statement for executing some code if \'i\' is NOT equal to 5?','if (i != 5)','if i <> 5','if i =! 5 then','if (i <> 5)','if (i != 5)',4),
(69,'How does a WHILE loop start?','while (i <= 10; i++)','while (i <= 10)','while i = 1 to 10','while i = 1 : 10','while (i <= 10)',4),
(70,'How does a FOR loop start?','for (i = 0; i <= 5)','for i = 1 to 5','for (i = 0; i <= 5; i++)','for (i <= 5; i++)','for (i = 0; i <= 5; i++)',4),
(71,'How can you add a comment in a JavaScript?','<!--This is a comment-->','//This is a comment','->This is a comment<-','%This is a comment%','//This is a comment',4),
(72,'What is the correct way to write a JavaScript array?','var colors = \'red\', \'green\', \'blue\'','var colors = 1 = (\'red\'), 2 = (\'green\'), 3 = (\'blue\')','var colors = [\'red\', \'green\', \'blue\']','var colors = (1:\'red\', 2:\'green\', 3:\'blue\')','var colors = [\'red\', \'green\', \'blue\']',4),
(73,'How do you round the number 7.25, to the nearest integer?','Math.rnd(7.25)','Math.round(7.25)','round(7.25)','rnd(7.25)','Math.round(7.25)',4),
(74,'How do you find the number with the highest value of x and y?','ceil(x, y)','top(x, y)','Math.ceil(x, y)','Math.max(x, y)','Math.max(x, y)',4),
(75,'How can you detect the client\'s browser name?','navigator.appName','browser.name','client.navName','nav.client.name','navigator.appName',4),
(76,'Which event occurs when the user clicks on an HTML element?','onmouseover','onmouseclick','onclick','onchange','onclick',4),
(77,'How do you declare a JavaScript variable?','var carName;','v carName;','variable carName;','carName;','var carName;',4),
(78,'Which operator is used to assign a value to a variable?','-','*','x','=','=',4),
(79,'What will the following code return: Boolean(10 > 9)','false','true','NaN','Undefined','true',4),
(80,'How to insert a comment that has more than one line?','//This comment hasmore than one line//','/*This comment has more than one line*/','<!--This comment has more than one line-->','#This comment has more than one line#','/*This comment has more than one line*/',4);